# Generated by Django 5.2.6 on 2025-09-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age_range',
            field=models.CharField(blank=True, choices=[('under_16', 'Under 16'), ('16_24', '16-24'), ('25_30', '25-30'), ('31_40', '31-40'), ('41_50', '41-50'), ('above_50', 'Above 50')], max_length=20, null=True),
        ),
    ]
