# Generated by Django 5.2.6 on 2025-09-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_age_userprofile_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Any other skincare concerns or goals'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_routine',
            field=models.CharField(blank=True, choices=[('none', 'No routine'), ('basic', 'Basic (cleanser + moisturizer)'), ('moderate', 'Moderate (3-5 products)'), ('extensive', 'Extensive (5+ products)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='main_concern',
            field=models.CharField(blank=True, choices=[('acne', 'Acne'), ('dryness', 'Dryness'), ('aging', 'Anti-aging'), ('sensitivity', 'Sensitivity'), ('oiliness', 'Excess oil')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='main_goal',
            field=models.CharField(blank=True, choices=[('clear_skin', 'Clear skin'), ('moisturized', 'Better hydration'), ('anti_aging', 'Anti-aging'), ('simple_routine', 'Simple routine')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefers_natural',
            field=models.BooleanField(default=False, help_text='I prefer natural/organic products'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skin_concerns',
            field=models.TextField(blank=True, help_text='Describe your main skin concerns'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('sensitive', 'Sensitive'), ('normal', 'Normal')], max_length=50, null=True),
        ),
    ]
