# Generated by Django 5.2.6 on 2025-09-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_age_userprofile_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_routine',
            field=models.CharField(blank=True, choices=[('none', 'No routine'), ('basic', 'Basic (cleanser + moisturizer)'), ('moderate', 'Moderate (3-5 products)'), ('extensive', 'Extensive (5+ products)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefers_cruelty_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefers_fragrance_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefers_vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skincare_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skin_concerns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('sensitive', 'Sensitive'), ('normal', 'Normal')], max_length=20, null=True),
        ),
    ]
