# Generated by Django 5.2.6 on 2025-09-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinestep',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routinestep',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10),
        ),
    ]
