# Generated by Django 5.2.6 on 2025-10-01 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('routines', '0002_routinestep_completed_routinestep_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinestep',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
