# Generated by Django 5.2.6 on 2025-10-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_routinestep_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routine',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='routine',
            name='routine_type',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('hair', 'Hair'), ('body', 'Body'), ('special', 'Special'), ('seasonal', 'Seasonal')], max_length=10),
        ),
    ]
