# Generated by Django 5.2.6 on 2025-10-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_alter_routine_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinestep',
            name='frequency',
            field=models.CharField(
                max_length=10,
                choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')],
                default='daily',
            ),
        ),
    ]
