# Generated by Django 5.2.6 on 2025-10-01 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('brand', models.CharField(help_text='Brand name', max_length=100)),
                ('product_type', models.CharField(choices=[('cleanser', 'Cleanser'), ('toner', 'Toner'), ('serum', 'Serum'), ('moisturizer', 'Moisturizer'), ('sunscreen', 'Sunscreen'), ('exfoliant', 'Exfoliant'), ('mask', 'Face Mask'), ('eye_cream', 'Eye Cream'), ('oil', 'Face Oil'), ('essence', 'Essence'), ('spot_treatment', 'Spot Treatment'), ('retinol', 'Retinol/Retinoid'), ('vitamin_c', 'Vitamin C'), ('other', 'Other')], help_text='Type of skincare product', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this product (ingredients, effects, etc.)', null=True)),
                ('image', models.ImageField(blank=True, help_text='Product image (optional)', null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['brand', 'name'],
                'unique_together': {('user', 'name', 'brand')},
            },
        ),
    ]
