# Generated by Django 5.2.6 on 2025-10-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Product description', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Product expiry date (important for skincare safety!)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, help_text='External ID from Open Beauty Facts', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Product ingredients list', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark as favorite/holy grail product'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '⭐ (1 star)'), (2, '⭐⭐ (2 stars)'), (3, '⭐⭐⭐ (3 stars)'), (4, '⭐⭐⭐⭐ (4 stars)'), (5, '⭐⭐⭐⭐⭐ (5 stars)')], help_text='Your personal rating (1-5 stars)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('all', 'All Skin Types'), ('dry', 'Dry'), ('oily', 'Oily'), ('combination', 'Combination'), ('sensitive', 'Sensitive'), ('normal', 'Normal'), ('acne_prone', 'Acne-Prone'), ('mature', 'Mature')], help_text='Recommended skin type for this product', max_length=20, null=True),
        ),
    ]
