# Generated by Django 5.2.6 on 2025-10-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description_product_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
